version: '2.0'

services:
  db:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: '${MYSQL_USERNAME}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    ports:
      - 3306:3306
    expose:
      - '3306'
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - chainmail-db:/var/lib/mysql

volumes:
  chainmail-db: